name: 'Turnstile ingestion'

footprint:
  model-graphs:
    - http://rack001/model
  data-graphs:
    - http://rack001/nist-800-53
    - http://rack001/mitre-cwe
    - http://rack001/turnstiledata

steps:
  - manifest: rack.yaml
  - model: ../GE-Ontology/OwlModels/import.yaml
  - data: ../RACK-Ontology/ontology/DO-178C/import.yaml
